---
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
      secrets:
        codecov_token:
          required: true
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Lint
        run: npm run lint
      - name: Test ${{ matrix.node-version }}
        run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
